// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5v1QK6FYGTdTQlGVJ15WszeUaDDoL_Vo',
    appId: '1:983432217303:web:0f60c88f1b806dcf762692',
    messagingSenderId: '983432217303',
    projectId: 'flutter-shop-app-a8de1',
    authDomain: 'flutter-shop-app-a8de1.firebaseapp.com',
    storageBucket: 'flutter-shop-app-a8de1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwZeIbziZjC-d-5Pj5W50r9ezJf10NfSw',
    appId: '1:983432217303:android:c6ea045534c6c42f762692',
    messagingSenderId: '983432217303',
    projectId: 'flutter-shop-app-a8de1',
    storageBucket: 'flutter-shop-app-a8de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsFH0kRgUa9UemZ7RxvH2Al1hmdmXwNWU',
    appId: '1:983432217303:ios:3afae6b87860dae6762692',
    messagingSenderId: '983432217303',
    projectId: 'flutter-shop-app-a8de1',
    storageBucket: 'flutter-shop-app-a8de1.appspot.com',
    iosClientId: '983432217303-cnspgbhkfdhlbtqo84j70t11jdau454r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsFH0kRgUa9UemZ7RxvH2Al1hmdmXwNWU',
    appId: '1:983432217303:ios:3afae6b87860dae6762692',
    messagingSenderId: '983432217303',
    projectId: 'flutter-shop-app-a8de1',
    storageBucket: 'flutter-shop-app-a8de1.appspot.com',
    iosClientId: '983432217303-cnspgbhkfdhlbtqo84j70t11jdau454r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
